### ISSUE TITLE
Rain

### ISSUE THREAD

**Issue by Dgzt** [JamesTKhan/Mundus#116]
**Describe the solution you'd like**
I think the rain feature would be useful.

**Comment by JamesTKhan** [comment]
Copied from Snow issue

This is too specific of a feature for Mundus I believe.

I think this is better solved by using a Particle System to create this kind of effect. I created a Snow effect in this jam game using particle system https://wjamesfl.itch.io/santa-is-coming.

We could look into integrating a ParticleComponent into Mundus down the road perhaps so that particles could be created in the editor. That should be a separate issue to consider implementing particles into the editor though.
