### ISSUE TITLE
Snowing

### ISSUE THREAD

**Issue by Dgzt** [JamesTKhan/Mundus#117]
**Describe the solution you'd like**
I think the snowing feature would be useful.

**Comment by JamesTKhan** [comment]
This is too specific of a feature for Mundus I believe. 

I think this is better solved by using a Particle System to create this kind of effect. I created a Snow effect in this jam game using particle system https://wjamesfl.itch.io/santa-is-coming.

We could look into integrating a ParticleComponent into Mundus down the road perhaps so that particles could be created in the editor. That should be a separate issue to consider implementing particles into the editor though.
